<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Hyperparameter-tuning Cookbook - 13&nbsp; Hyperparameter Tuning for PyTorch With spotPython</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./24_spot_torch_regression.html" rel="next">
<link href="./12_spot_hpt_torch_cifar10.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta name="twitter:title" content="Hyperparameter-tuning Cookbook - 13&nbsp; Hyperparameter Tuning for PyTorch With spotPython">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="./figures/14-torch_p040025_10min_5init_2023-06-07_12-41-06_tensorboard_01.png">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./14_spot_ray_hpt_torch_cifar10.html"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Hyperparameter Tuning for PyTorch With `spotPython`</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Hyperparameter-tuning Cookbook</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/sequential-parameter-optimization/spotPython" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="./Hyperparameter-tuning-Cookbook.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_spot_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction: Hyperparameter Tuning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_spot_multidim.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Multi-dimensional Functions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_spot_anisotropic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Isotropic and Anisotropic Kriging</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_spot_sklearn_surrogate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Using <code>sklearn</code> Surrogates in <code>spotPython</code></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_spot_sklearn_optimization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Sequential Parameter Optimization: Using <code>scipy</code> Optimizers</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_spot_gaussian.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Sequential Parameter Optimization: Gaussian Process Models</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_spot_ei.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Expected Improvement</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_spot_noisy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Hyperparameter Tuning and Noise</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_spot_ocba.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Handling Noise: Optimal Computational Budget Allocation in <code>Spot</code></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10_spot_hpt_sklearn_classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Hyperparameter Tuning: sklearn</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11_spot_hpt_torch_fashion_mnist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Hyperparameter Tuning: PyTorch With fashionMNIST Data Using Hold-out Data Sets</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12_spot_hpt_torch_cifar10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Hyperparameter Tuning: PyTorch wth cifar10 Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14_spot_ray_hpt_torch_cifar10.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Hyperparameter Tuning for PyTorch With <code>spotPython</code></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./24_spot_torch_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Hyperparameter Tuning for PyTorch With <code>spotPython</code>: Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./99_spot_doc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Documentation of the Sequential Parameter Optimization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-setup" id="toc-sec-setup" class="nav-link active" data-scroll-target="#sec-setup"><span class="header-section-number">13.1</span> Setup</a></li>
  <li><a href="#initialization-of-the-fun_control-dictionary" id="toc-initialization-of-the-fun_control-dictionary" class="nav-link" data-scroll-target="#initialization-of-the-fun_control-dictionary"><span class="header-section-number">13.2</span> Initialization of the <code>fun_control</code> Dictionary</a></li>
  <li><a href="#sec-data-loading" id="toc-sec-data-loading" class="nav-link" data-scroll-target="#sec-data-loading"><span class="header-section-number">13.3</span> Data Loading</a></li>
  <li><a href="#sec-the-model-to-be-tuned" id="toc-sec-the-model-to-be-tuned" class="nav-link" data-scroll-target="#sec-the-model-to-be-tuned"><span class="header-section-number">13.4</span> The Model (Algorithm) to be Tuned</a>
  <ul class="collapse">
  <li><a href="#sec-specification-of-preprocessing-model" id="toc-sec-specification-of-preprocessing-model" class="nav-link" data-scroll-target="#sec-specification-of-preprocessing-model"><span class="header-section-number">13.4.1</span> Specification of the Preprocessing Model</a></li>
  <li><a href="#sec-selection-of-the-algorithm" id="toc-sec-selection-of-the-algorithm" class="nav-link" data-scroll-target="#sec-selection-of-the-algorithm"><span class="header-section-number">13.4.2</span> Select <code>algorithm</code> and <code>core_model_hyper_dict</code></a></li>
  <li><a href="#the-net_core-class" id="toc-the-net_core-class" class="nav-link" data-scroll-target="#the-net_core-class"><span class="header-section-number">13.4.3</span> The <code>Net_Core</code> class</a></li>
  <li><a href="#sec-comparison" id="toc-sec-comparison" class="nav-link" data-scroll-target="#sec-comparison"><span class="header-section-number">13.4.4</span> Comparison of the Approach Described in the PyTorch Tutorial With spotPython</a></li>
  </ul></li>
  <li><a href="#sec-search-space" id="toc-sec-search-space" class="nav-link" data-scroll-target="#sec-search-space"><span class="header-section-number">13.5</span> The Search Space: Hyperparameters</a>
  <ul class="collapse">
  <li><a href="#sec-configuring-the-search-space-with-ray-tune" id="toc-sec-configuring-the-search-space-with-ray-tune" class="nav-link" data-scroll-target="#sec-configuring-the-search-space-with-ray-tune"><span class="header-section-number">13.5.1</span> Configuring the Search Space With Ray Tune</a></li>
  <li><a href="#sec-configuring-the-search-space-with-spotpython" id="toc-sec-configuring-the-search-space-with-spotpython" class="nav-link" data-scroll-target="#sec-configuring-the-search-space-with-spotpython"><span class="header-section-number">13.5.2</span> Configuring the Search Space With spotPython</a></li>
  <li><a href="#sec-modification-of-hyperparameters" id="toc-sec-modification-of-hyperparameters" class="nav-link" data-scroll-target="#sec-modification-of-hyperparameters"><span class="header-section-number">13.5.3</span> Modifying the Hyperparameters</a></li>
  </ul></li>
  <li><a href="#sec-optimizers" id="toc-sec-optimizers" class="nav-link" data-scroll-target="#sec-optimizers"><span class="header-section-number">13.6</span> Optimizers</a></li>
  <li><a href="#sec-data-splitting" id="toc-sec-data-splitting" class="nav-link" data-scroll-target="#sec-data-splitting"><span class="header-section-number">13.7</span> Evaluation: Data Splitting</a>
  <ul class="collapse">
  <li><a href="#hold-out-data-split" id="toc-hold-out-data-split" class="nav-link" data-scroll-target="#hold-out-data-split"><span class="header-section-number">13.7.1</span> Hold-out Data Split</a></li>
  <li><a href="#cross-validation" id="toc-cross-validation" class="nav-link" data-scroll-target="#cross-validation"><span class="header-section-number">13.7.2</span> Cross-Validation</a></li>
  <li><a href="#overview-of-the-evaluation-settings" id="toc-overview-of-the-evaluation-settings" class="nav-link" data-scroll-target="#overview-of-the-evaluation-settings"><span class="header-section-number">13.7.3</span> Overview of the Evaluation Settings</a></li>
  </ul></li>
  <li><a href="#sec-loss-functions" id="toc-sec-loss-functions" class="nav-link" data-scroll-target="#sec-loss-functions"><span class="header-section-number">13.8</span> Evaluation: Loss Functions and Metrics</a></li>
  <li><a href="#sec-prepare-spot-call" id="toc-sec-prepare-spot-call" class="nav-link" data-scroll-target="#sec-prepare-spot-call"><span class="header-section-number">13.9</span> Preparing the SPOT Call</a></li>
  <li><a href="#sec-the-objective-function" id="toc-sec-the-objective-function" class="nav-link" data-scroll-target="#sec-the-objective-function"><span class="header-section-number">13.10</span> The Objective Function <code>fun_torch</code></a></li>
  <li><a href="#sec-default-hyperparameters" id="toc-sec-default-hyperparameters" class="nav-link" data-scroll-target="#sec-default-hyperparameters"><span class="header-section-number">13.11</span> Using Default Hyperparameters or Results from Previous Runs</a></li>
  <li><a href="#sec-call-the-hyperparameter-tuner" id="toc-sec-call-the-hyperparameter-tuner" class="nav-link" data-scroll-target="#sec-call-the-hyperparameter-tuner"><span class="header-section-number">13.12</span> Starting the Hyperparameter Tuning</a></li>
  <li><a href="#sec-tensorboard" id="toc-sec-tensorboard" class="nav-link" data-scroll-target="#sec-tensorboard"><span class="header-section-number">13.13</span> Tensorboard</a>
  <ul class="collapse">
  <li><a href="#tensorboard-start-tensorboard" id="toc-tensorboard-start-tensorboard" class="nav-link" data-scroll-target="#tensorboard-start-tensorboard"><span class="header-section-number">13.13.1</span> Tensorboard: Start Tensorboard</a></li>
  <li><a href="#sec-saving-the-state-of-the-notebook" id="toc-sec-saving-the-state-of-the-notebook" class="nav-link" data-scroll-target="#sec-saving-the-state-of-the-notebook"><span class="header-section-number">13.13.2</span> Saving the State of the Notebook</a></li>
  </ul></li>
  <li><a href="#sec-results" id="toc-sec-results" class="nav-link" data-scroll-target="#sec-results"><span class="header-section-number">13.14</span> Results</a>
  <ul class="collapse">
  <li><a href="#sec-get-spot-results" id="toc-sec-get-spot-results" class="nav-link" data-scroll-target="#sec-get-spot-results"><span class="header-section-number">13.14.1</span> Get SPOT Results</a></li>
  <li><a href="#get-default-hyperparameters" id="toc-get-default-hyperparameters" class="nav-link" data-scroll-target="#get-default-hyperparameters"><span class="header-section-number">13.14.2</span> Get Default Hyperparameters</a></li>
  <li><a href="#evaluation-of-the-default-architecture" id="toc-evaluation-of-the-default-architecture" class="nav-link" data-scroll-target="#evaluation-of-the-default-architecture"><span class="header-section-number">13.14.3</span> Evaluation of the Default Architecture</a></li>
  <li><a href="#evaluation-of-the-tuned-architecture" id="toc-evaluation-of-the-tuned-architecture" class="nav-link" data-scroll-target="#evaluation-of-the-tuned-architecture"><span class="header-section-number">13.14.4</span> Evaluation of the Tuned Architecture</a></li>
  <li><a href="#comparison-with-default-hyperparameters-and-ray-tune" id="toc-comparison-with-default-hyperparameters-and-ray-tune" class="nav-link" data-scroll-target="#comparison-with-default-hyperparameters-and-ray-tune"><span class="header-section-number">13.14.5</span> Comparison with Default Hyperparameters and Ray Tune</a></li>
  <li><a href="#detailed-hyperparameter-plots" id="toc-detailed-hyperparameter-plots" class="nav-link" data-scroll-target="#detailed-hyperparameter-plots"><span class="header-section-number">13.14.6</span> Detailed Hyperparameter Plots</a></li>
  </ul></li>
  <li><a href="#sec-summary" id="toc-sec-summary" class="nav-link" data-scroll-target="#sec-summary"><span class="header-section-number">13.15</span> Summary and Outlook</a></li>
  <li><a href="#sec-appendix" id="toc-sec-appendix" class="nav-link" data-scroll-target="#sec-appendix"><span class="header-section-number">13.16</span> Appendix</a>
  <ul class="collapse">
  <li><a href="#sample-output-from-ray-tunes-run" id="toc-sample-output-from-ray-tunes-run" class="nav-link" data-scroll-target="#sample-output-from-ray-tunes-run"><span class="header-section-number">13.16.1</span> Sample Output From Ray Tune’s Run</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-hyperparameter-tuning-for-pytorch" class="quarto-section-identifier"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Hyperparameter Tuning for PyTorch With <code>spotPython</code></span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>In this tutorial, we will show how <code>spotPython</code> can be integrated into the <code>PyTorch</code> training workflow. It is based on the tutorial “Hyperparameter Tuning with Ray Tune” from the <code>PyTorch</code> documentation <span class="citation" data-cites="pyto23a">(<a href="references.html#ref-pyto23a" role="doc-biblioref">PyTorch 2023a</a>)</span>, which is an extension of the tutorial “Training a Classifier” <span class="citation" data-cites="pyto23b">(<a href="references.html#ref-pyto23b" role="doc-biblioref">PyTorch 2023b</a>)</span> for training a CIFAR10 image classifier.</p>
<p>This document refers to the following software versions:</p>
<ul>
<li><code>python</code>: 3.10.10</li>
<li><code>torch</code>: 2.0.1</li>
<li><code>torchvision</code>: 0.15.0</li>
<li><code>spotPython</code>: 0.2.15</li>
</ul>
<p><code>spotPython</code> can be installed via pip<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
<pre class="{raw}"><code>!pip install spotPython</code></pre>
<p>Results that refer to the <code>Ray Tune</code> package are taken from <a href="https://PyTorch.org/tutorials/beginner/hyperparameter_tuning_tutorial.html">https://PyTorch.org/tutorials/beginner/hyperparameter_tuning_tutorial.html</a><a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>.</p>
<section id="sec-setup" class="level2" data-number="13.1">
<h2 data-number="13.1" class="anchored" data-anchor-id="sec-setup"><span class="header-section-number">13.1</span> Setup</h2>
<p>Before we consider the detailed experimental setup, we select the parameters that affect run time, initial design size and the device that is used.</p>
<div class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>MAX_TIME <span class="op">=</span> <span class="dv">60</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>INIT_SIZE <span class="op">=</span> <span class="dv">20</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>DEVICE <span class="op">=</span> <span class="st">"cpu"</span> <span class="co"># "cuda:0"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="initialization-of-the-fun_control-dictionary" class="level2" data-number="13.2">
<h2 data-number="13.2" class="anchored" data-anchor-id="initialization-of-the-fun_control-dictionary"><span class="header-section-number">13.2</span> Initialization of the <code>fun_control</code> Dictionary</h2>
<p><code>spotPython</code> uses a Python dictionary for storing the information required for the hyperparameter tuning process. This dictionary is called <code>fun_control</code> and is initialized with the function <code>fun_control_init</code>. The function <code>fun_control_init</code> returns a skeleton dictionary. The dictionary is filled with the required information for the hyperparameter tuning process. It stores the hyperparameter tuning settings, e.g., the deep learning network architecture that should be tuned, the classification (or regression) problem, and the data that is used for the tuning. The dictionary is used as an input for the SPOT function.</p>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> spotPython.utils.init <span class="im">import</span> fun_control_init</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>fun_control <span class="op">=</span> fun_control_init(task<span class="op">=</span><span class="st">"classification"</span>,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    tensorboard_path<span class="op">=</span><span class="st">"runs/14_spot_ray_hpt_torch_cifar10"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="sec-data-loading" class="level2" data-number="13.3">
<h2 data-number="13.3" class="anchored" data-anchor-id="sec-data-loading"><span class="header-section-number">13.3</span> Data Loading</h2>
<p>The data loading process is implemented in the same manner as described in the Section “Data loaders” in <span class="citation" data-cites="pyto23a">PyTorch (<a href="references.html#ref-pyto23a" role="doc-biblioref">2023a</a>)</span>. The data loaders are wrapped into the function <code>load_data_cifar10</code> which is identical to the function <code>load_data</code> in <span class="citation" data-cites="pyto23a">PyTorch (<a href="references.html#ref-pyto23a" role="doc-biblioref">2023a</a>)</span>. A global data directory is used, which allows sharing the data directory between different trials. The method <code>load_data_cifar10</code> is part of the <code>spotPython</code> package and can be imported from <code>spotPython.data.torchdata</code>.</p>
<p>In the following step, the test and train data are added to the dictionary <code>fun_control</code>.</p>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> spotPython.data.torchdata <span class="im">import</span> load_data_cifar10</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>train, test <span class="op">=</span> load_data_cifar10()</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>n_samples <span class="op">=</span> <span class="bu">len</span>(train)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># add the dataset to the fun_control</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>fun_control.update({</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"train"</span>: train,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"test"</span>: test,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"n_samples"</span>: n_samples})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="sec-the-model-to-be-tuned" class="level2" data-number="13.4">
<h2 data-number="13.4" class="anchored" data-anchor-id="sec-the-model-to-be-tuned"><span class="header-section-number">13.4</span> The Model (Algorithm) to be Tuned</h2>
<section id="sec-specification-of-preprocessing-model" class="level3" data-number="13.4.1">
<h3 data-number="13.4.1" class="anchored" data-anchor-id="sec-specification-of-preprocessing-model"><span class="header-section-number">13.4.1</span> Specification of the Preprocessing Model</h3>
<p>After the training and test data are specified and added to the <code>fun_control</code> dictionary, <code>spotPython</code> allows the specification of a data preprocessing pipeline, e.g., for the scaling of the data or for the one-hot encoding of categorical variables. The preprocessing model is called <code>prep_model</code> (“preparation” or pre-processing) and includes steps that are not subject to the hyperparameter tuning process. The preprocessing model is specified in the <code>fun_control</code> dictionary. The preprocessing model can be implemented as a <code>sklearn</code> pipeline. The following code shows a typical preprocessing pipeline:</p>
<pre class="{raw}"><code>categorical_columns = ["cities", "colors"]
one_hot_encoder = OneHotEncoder(handle_unknown="ignore",
                                    sparse_output=False)
prep_model = ColumnTransformer(
        transformers=[
             ("categorical", one_hot_encoder, categorical_columns),
         ],
         remainder=StandardScaler(),
     )</code></pre>
<p>Because the Ray Tune (<code>ray[tune]</code>) hyperparameter tuning as described in <span class="citation" data-cites="pyto23a">PyTorch (<a href="references.html#ref-pyto23a" role="doc-biblioref">2023a</a>)</span> does not use a preprocessing model, the preprocessing model is set to <code>None</code> here.</p>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>prep_model <span class="op">=</span> <span class="va">None</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>fun_control.update({<span class="st">"prep_model"</span>: prep_model})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="sec-selection-of-the-algorithm" class="level3" data-number="13.4.2">
<h3 data-number="13.4.2" class="anchored" data-anchor-id="sec-selection-of-the-algorithm"><span class="header-section-number">13.4.2</span> Select <code>algorithm</code> and <code>core_model_hyper_dict</code></h3>
<p>The same neural network model as implemented in the section “Configurable neural network” of the <code>PyTorch</code> tutorial <span class="citation" data-cites="pyto23a">(<a href="references.html#ref-pyto23a" role="doc-biblioref">PyTorch 2023a</a>)</span> is used here. We will show the implementation from <span class="citation" data-cites="pyto23a">PyTorch (<a href="references.html#ref-pyto23a" role="doc-biblioref">2023a</a>)</span> in <a href="#sec-implementation-with-raytune"><span>Section&nbsp;13.4.2.1</span></a> first, before the extended implementation with <code>spotPython</code> is shown in <a href="#sec-implementation-with-spotpython"><span>Section&nbsp;13.4.2.2</span></a>.</p>
<section id="sec-implementation-with-raytune" class="level4" data-number="13.4.2.1">
<h4 data-number="13.4.2.1" class="anchored" data-anchor-id="sec-implementation-with-raytune"><span class="header-section-number">13.4.2.1</span> Implementing a Configurable Neural Network With Ray Tune</h4>
<p>We used the same hyperparameters that are implemented as configurable in the <code>PyTorch</code> tutorial. We specify the layer sizes, namely <code>l1</code> and <code>l2</code>, of the fully connected layers:</p>
<pre class="{raw}"><code>class Net(nn.Module):
    def __init__(self, l1=120, l2=84):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, l1)
        self.fc2 = nn.Linear(l1, l2)
        self.fc3 = nn.Linear(l2, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16 * 5 * 5)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
</code></pre>
<p>The learning rate, i.e., <code>lr</code>, of the optimizer is made configurable, too:</p>
<pre class="{raw}"><code>optimizer = optim.SGD(net.parameters(), lr=config["lr"], momentum=0.9)</code></pre>
</section>
<section id="sec-implementation-with-spotpython" class="level4" data-number="13.4.2.2">
<h4 data-number="13.4.2.2" class="anchored" data-anchor-id="sec-implementation-with-spotpython"><span class="header-section-number">13.4.2.2</span> Implementing a Configurable Neural Network With spotPython</h4>
<p><code>spotPython</code> implements a class which is similar to the class described in the <code>PyTorch</code> tutorial. The class is called <code>Net_CIFAR10</code> and is implemented in the file <code>netcifar10.py</code>.</p>
<pre class="{raw}"><code>from torch import nn
import torch.nn.functional as F
import spotPython.torch.netcore as netcore


class Net_CIFAR10(netcore.Net_Core):
    def __init__(self, l1, l2, lr_mult, batch_size, epochs, k_folds, patience,
    optimizer, sgd_momentum):
        super(Net_CIFAR10, self).__init__(
            lr_mult=lr_mult,
            batch_size=batch_size,
            epochs=epochs,
            k_folds=k_folds,
            patience=patience,
            optimizer=optimizer,
            sgd_momentum=sgd_momentum,
        )
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, l1)
        self.fc2 = nn.Linear(l1, l2)
        self.fc3 = nn.Linear(l2, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16 * 5 * 5)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x</code></pre>
</section>
</section>
<section id="the-net_core-class" class="level3" data-number="13.4.3">
<h3 data-number="13.4.3" class="anchored" data-anchor-id="the-net_core-class"><span class="header-section-number">13.4.3</span> The <code>Net_Core</code> class</h3>
<p><code>Net_CIFAR10</code> inherits from the class <code>Net_Core</code> which is implemented in the file <code>netcore.py</code>. It implements the additional attributes that are common to all neural network models. The <code>Net_Core</code> class is implemented in the file <code>netcore.py</code>. It implements hyperparameters as attributes, that are not used by the <code>core_model</code>, e.g.:</p>
<ul>
<li>optimizer (<code>optimizer</code>),</li>
<li>learning rate (<code>lr</code>),</li>
<li>batch size (<code>batch_size</code>),</li>
<li>epochs (<code>epochs</code>),</li>
<li>k_folds (<code>k_folds</code>), and</li>
<li>early stopping criterion “patience” (<code>patience</code>).</li>
</ul>
<p>Users can add further attributes to the class. The class <code>Net_Core</code> is shown below.</p>
<pre class="{raw}"><code>from torch import nn


class Net_Core(nn.Module):
    def __init__(self, lr_mult, batch_size, epochs, k_folds, patience,
        optimizer, sgd_momentum):
        super(Net_Core, self).__init__()
        self.lr_mult = lr_mult
        self.batch_size = batch_size
        self.epochs = epochs
        self.k_folds = k_folds
        self.patience = patience
        self.optimizer = optimizer
        self.sgd_momentum = sgd_momentum</code></pre>
</section>
<section id="sec-comparison" class="level3" data-number="13.4.4">
<h3 data-number="13.4.4" class="anchored" data-anchor-id="sec-comparison"><span class="header-section-number">13.4.4</span> Comparison of the Approach Described in the PyTorch Tutorial With spotPython</h3>
<p>Comparing the class <code>Net</code> from the <code>PyTorch</code> tutorial and the class <code>Net_CIFAR10</code> from <code>spotPython</code>, we see that the class <code>Net_CIFAR10</code> has additional attributes and does not inherit from <code>nn</code> directly. It adds an additional class, <code>Net_core</code>, that takes care of additional attributes that are common to all neural network models, e.g., the learning rate multiplier <code>lr_mult</code> or the batch size <code>batch_size</code>.</p>
<p><code>spotPython</code>’s <code>core_model</code> implements an instance of the <code>Net_CIFAR10</code> class. In addition to the basic neural network model, the <code>core_model</code> can use these additional attributes. <code>spotPython</code> provides methods for handling these additional attributes to guarantee 100% compatibility with the <code>PyTorch</code> classes. The method <code>add_core_model_to_fun_control</code> adds the hyperparameters and additional attributes to the <code>fun_control</code> dictionary. The method is shown below.</p>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> spotPython.torch.netcifar10 <span class="im">import</span> Net_CIFAR10</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> spotPython.data.torch_hyper_dict <span class="im">import</span> TorchHyperDict</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> spotPython.hyperparameters.values <span class="im">import</span> add_core_model_to_fun_control</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>core_model <span class="op">=</span> Net_CIFAR10</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>fun_control <span class="op">=</span> add_core_model_to_fun_control(core_model<span class="op">=</span>core_model,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>                              fun_control<span class="op">=</span>fun_control,</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>                              hyper_dict<span class="op">=</span>TorchHyperDict,</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>                              filename<span class="op">=</span><span class="va">None</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="sec-search-space" class="level2" data-number="13.5">
<h2 data-number="13.5" class="anchored" data-anchor-id="sec-search-space"><span class="header-section-number">13.5</span> The Search Space: Hyperparameters</h2>
<p>In <a href="#sec-configuring-the-search-space-with-ray-tune"><span>Section&nbsp;13.5.1</span></a>, we first describe how to configure the search space with <code>ray[tune]</code> (as shown in <span class="citation" data-cites="pyto23a">PyTorch (<a href="references.html#ref-pyto23a" role="doc-biblioref">2023a</a>)</span>) and then how to configure the search space with <code>spotPython</code> in <a href="#sec-configuring-the-search-space-with-spotpython"><span>Section&nbsp;13.5.2</span></a>.</p>
<section id="sec-configuring-the-search-space-with-ray-tune" class="level3" data-number="13.5.1">
<h3 data-number="13.5.1" class="anchored" data-anchor-id="sec-configuring-the-search-space-with-ray-tune"><span class="header-section-number">13.5.1</span> Configuring the Search Space With Ray Tune</h3>
<p>Ray Tune’s search space can be configured as follows <span class="citation" data-cites="pyto23a">(<a href="references.html#ref-pyto23a" role="doc-biblioref">PyTorch 2023a</a>)</span>:</p>
<pre class="{raw}"><code>config = {
    "l1": tune.sample_from(lambda _: 2**np.random.randint(2, 9)),
    "l2": tune.sample_from(lambda _: 2**np.random.randint(2, 9)),
    "lr": tune.loguniform(1e-4, 1e-1),
    "batch_size": tune.choice([2, 4, 8, 16])
}</code></pre>
<p>The <code>tune.sample_from()</code> function enables the user to define sample methods to obtain hyperparameters. In this example, the <code>l1</code> and <code>l2</code> parameters should be powers of 2 between 4 and 256, so either 4, 8, 16, 32, 64, 128, or 256. The <code>lr</code> (learning rate) should be uniformly sampled between 0.0001 and 0.1. Lastly, the batch size is a choice between 2, 4, 8, and 16.</p>
<p>At each trial, <code>ray[tune]</code> will randomly sample a combination of parameters from these search spaces. It will then train a number of models in parallel and find the best performing one among these. <code>ray[tune]</code> uses the <code>ASHAScheduler</code> which will terminate bad performing trials early.</p>
</section>
<section id="sec-configuring-the-search-space-with-spotpython" class="level3" data-number="13.5.2">
<h3 data-number="13.5.2" class="anchored" data-anchor-id="sec-configuring-the-search-space-with-spotpython"><span class="header-section-number">13.5.2</span> Configuring the Search Space With spotPython</h3>
<section id="the-hyper_dict-hyperparameters-for-the-selected-algorithm" class="level4" data-number="13.5.2.1">
<h4 data-number="13.5.2.1" class="anchored" data-anchor-id="the-hyper_dict-hyperparameters-for-the-selected-algorithm"><span class="header-section-number">13.5.2.1</span> The <code>hyper_dict</code> Hyperparameters for the Selected Algorithm</h4>
<p><code>spotPython</code> uses <code>JSON</code> files for the specification of the hyperparameters. Users can specify their individual <code>JSON</code> files, or they can use the <code>JSON</code> files provided by <code>spotPython</code>. The <code>JSON</code> file for the <code>core_model</code> is called <code>torch_hyper_dict.json</code>.</p>
<p>In contrast to <code>ray[tune]</code>, <code>spotPython</code> can handle numerical, boolean, and categorical hyperparameters. They can be specified in the <code>JSON</code> file in a similar way as the numerical hyperparameters as shown below. Each entry in the <code>JSON</code> file represents one hyperparameter with the following structure: <code>type</code>, <code>default</code>, <code>transform</code>, <code>lower</code>, and <code>upper</code>.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode json code-with-copy"><code class="sourceCode json"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="er">"factor_hyperparameter":</span> <span class="fu">{</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    <span class="dt">"levels"</span><span class="fu">:</span> <span class="ot">[</span><span class="st">"A"</span><span class="ot">,</span> <span class="st">"B"</span><span class="ot">,</span> <span class="st">"C"</span><span class="ot">]</span><span class="fu">,</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    <span class="dt">"type"</span><span class="fu">:</span> <span class="st">"factor"</span><span class="fu">,</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    <span class="dt">"default"</span><span class="fu">:</span> <span class="st">"B"</span><span class="fu">,</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    <span class="dt">"transform"</span><span class="fu">:</span> <span class="st">"None"</span><span class="fu">,</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    <span class="dt">"core_model_parameter_type"</span><span class="fu">:</span> <span class="st">"str"</span><span class="fu">,</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    <span class="dt">"lower"</span><span class="fu">:</span> <span class="dv">0</span><span class="fu">,</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>    <span class="dt">"upper"</span><span class="fu">:</span> <span class="dv">2</span><span class="fu">}</span><span class="er">,</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The corresponding entries for the <code>Net_CIFAR10</code> class are shown below.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode json code-with-copy"><code class="sourceCode json"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">{</span><span class="dt">"Net_CIFAR10"</span><span class="fu">:</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">{</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>        <span class="dt">"l1"</span><span class="fu">:</span> <span class="fu">{</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"type"</span><span class="fu">:</span> <span class="st">"int"</span><span class="fu">,</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"default"</span><span class="fu">:</span> <span class="dv">5</span><span class="fu">,</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"transform"</span><span class="fu">:</span> <span class="st">"transform_power_2_int"</span><span class="fu">,</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"lower"</span><span class="fu">:</span> <span class="dv">2</span><span class="fu">,</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"upper"</span><span class="fu">:</span> <span class="dv">9</span><span class="fu">},</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>        <span class="dt">"l2"</span><span class="fu">:</span> <span class="fu">{</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"type"</span><span class="fu">:</span> <span class="st">"int"</span><span class="fu">,</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"default"</span><span class="fu">:</span> <span class="dv">5</span><span class="fu">,</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"transform"</span><span class="fu">:</span> <span class="st">"transform_power_2_int"</span><span class="fu">,</span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"lower"</span><span class="fu">:</span> <span class="dv">2</span><span class="fu">,</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"upper"</span><span class="fu">:</span> <span class="dv">9</span><span class="fu">},</span></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>        <span class="dt">"lr_mult"</span><span class="fu">:</span> <span class="fu">{</span></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"type"</span><span class="fu">:</span> <span class="st">"float"</span><span class="fu">,</span></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"default"</span><span class="fu">:</span> <span class="fl">1.0</span><span class="fu">,</span></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"transform"</span><span class="fu">:</span> <span class="st">"None"</span><span class="fu">,</span></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"lower"</span><span class="fu">:</span> <span class="fl">0.1</span><span class="fu">,</span></span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"upper"</span><span class="fu">:</span> <span class="dv">10</span><span class="fu">},</span></span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>        <span class="dt">"batch_size"</span><span class="fu">:</span> <span class="fu">{</span></span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"type"</span><span class="fu">:</span> <span class="st">"int"</span><span class="fu">,</span></span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"default"</span><span class="fu">:</span> <span class="dv">4</span><span class="fu">,</span></span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"transform"</span><span class="fu">:</span> <span class="st">"transform_power_2_int"</span><span class="fu">,</span></span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"lower"</span><span class="fu">:</span> <span class="dv">1</span><span class="fu">,</span></span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"upper"</span><span class="fu">:</span> <span class="dv">4</span><span class="fu">},</span></span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a>        <span class="dt">"epochs"</span><span class="fu">:</span> <span class="fu">{</span></span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"type"</span><span class="fu">:</span> <span class="st">"int"</span><span class="fu">,</span></span>
<span id="cb14-29"><a href="#cb14-29" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"default"</span><span class="fu">:</span> <span class="dv">3</span><span class="fu">,</span></span>
<span id="cb14-30"><a href="#cb14-30" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"transform"</span><span class="fu">:</span> <span class="st">"transform_power_2_int"</span><span class="fu">,</span></span>
<span id="cb14-31"><a href="#cb14-31" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"lower"</span><span class="fu">:</span> <span class="dv">1</span><span class="fu">,</span></span>
<span id="cb14-32"><a href="#cb14-32" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"upper"</span><span class="fu">:</span> <span class="dv">4</span><span class="fu">},</span></span>
<span id="cb14-33"><a href="#cb14-33" aria-hidden="true" tabindex="-1"></a>        <span class="dt">"k_folds"</span><span class="fu">:</span> <span class="fu">{</span></span>
<span id="cb14-34"><a href="#cb14-34" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"type"</span><span class="fu">:</span> <span class="st">"int"</span><span class="fu">,</span></span>
<span id="cb14-35"><a href="#cb14-35" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"default"</span><span class="fu">:</span> <span class="dv">2</span><span class="fu">,</span></span>
<span id="cb14-36"><a href="#cb14-36" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"transform"</span><span class="fu">:</span> <span class="st">"None"</span><span class="fu">,</span></span>
<span id="cb14-37"><a href="#cb14-37" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"lower"</span><span class="fu">:</span> <span class="dv">2</span><span class="fu">,</span></span>
<span id="cb14-38"><a href="#cb14-38" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"upper"</span><span class="fu">:</span> <span class="dv">3</span><span class="fu">},</span></span>
<span id="cb14-39"><a href="#cb14-39" aria-hidden="true" tabindex="-1"></a>        <span class="dt">"patience"</span><span class="fu">:</span> <span class="fu">{</span></span>
<span id="cb14-40"><a href="#cb14-40" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"type"</span><span class="fu">:</span> <span class="st">"int"</span><span class="fu">,</span></span>
<span id="cb14-41"><a href="#cb14-41" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"default"</span><span class="fu">:</span> <span class="dv">5</span><span class="fu">,</span></span>
<span id="cb14-42"><a href="#cb14-42" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"transform"</span><span class="fu">:</span> <span class="st">"None"</span><span class="fu">,</span></span>
<span id="cb14-43"><a href="#cb14-43" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"lower"</span><span class="fu">:</span> <span class="dv">2</span><span class="fu">,</span></span>
<span id="cb14-44"><a href="#cb14-44" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"upper"</span><span class="fu">:</span> <span class="dv">10</span><span class="fu">},</span></span>
<span id="cb14-45"><a href="#cb14-45" aria-hidden="true" tabindex="-1"></a>        <span class="dt">"optimizer"</span><span class="fu">:</span> <span class="fu">{</span></span>
<span id="cb14-46"><a href="#cb14-46" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"levels"</span><span class="fu">:</span> <span class="ot">[</span><span class="st">"Adadelta"</span><span class="ot">,</span></span>
<span id="cb14-47"><a href="#cb14-47" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"Adagrad"</span><span class="ot">,</span></span>
<span id="cb14-48"><a href="#cb14-48" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"Adam"</span><span class="ot">,</span></span>
<span id="cb14-49"><a href="#cb14-49" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"AdamW"</span><span class="ot">,</span></span>
<span id="cb14-50"><a href="#cb14-50" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"SparseAdam"</span><span class="ot">,</span></span>
<span id="cb14-51"><a href="#cb14-51" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"Adamax"</span><span class="ot">,</span></span>
<span id="cb14-52"><a href="#cb14-52" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"ASGD"</span><span class="ot">,</span></span>
<span id="cb14-53"><a href="#cb14-53" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"LBFGS"</span><span class="ot">,</span></span>
<span id="cb14-54"><a href="#cb14-54" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"NAdam"</span><span class="ot">,</span></span>
<span id="cb14-55"><a href="#cb14-55" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"RAdam"</span><span class="ot">,</span></span>
<span id="cb14-56"><a href="#cb14-56" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"RMSprop"</span><span class="ot">,</span></span>
<span id="cb14-57"><a href="#cb14-57" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"Rprop"</span><span class="ot">,</span></span>
<span id="cb14-58"><a href="#cb14-58" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"SGD"</span><span class="ot">]</span><span class="fu">,</span></span>
<span id="cb14-59"><a href="#cb14-59" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"type"</span><span class="fu">:</span> <span class="st">"factor"</span><span class="fu">,</span></span>
<span id="cb14-60"><a href="#cb14-60" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"default"</span><span class="fu">:</span> <span class="st">"SGD"</span><span class="fu">,</span></span>
<span id="cb14-61"><a href="#cb14-61" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"transform"</span><span class="fu">:</span> <span class="st">"None"</span><span class="fu">,</span></span>
<span id="cb14-62"><a href="#cb14-62" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"class_name"</span><span class="fu">:</span> <span class="st">"torch.optim"</span><span class="fu">,</span></span>
<span id="cb14-63"><a href="#cb14-63" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"core_model_parameter_type"</span><span class="fu">:</span> <span class="st">"str"</span><span class="fu">,</span></span>
<span id="cb14-64"><a href="#cb14-64" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"lower"</span><span class="fu">:</span> <span class="dv">0</span><span class="fu">,</span></span>
<span id="cb14-65"><a href="#cb14-65" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"upper"</span><span class="fu">:</span> <span class="dv">12</span><span class="fu">},</span></span>
<span id="cb14-66"><a href="#cb14-66" aria-hidden="true" tabindex="-1"></a>        <span class="dt">"sgd_momentum"</span><span class="fu">:</span> <span class="fu">{</span></span>
<span id="cb14-67"><a href="#cb14-67" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"type"</span><span class="fu">:</span> <span class="st">"float"</span><span class="fu">,</span></span>
<span id="cb14-68"><a href="#cb14-68" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"default"</span><span class="fu">:</span> <span class="fl">0.0</span><span class="fu">,</span></span>
<span id="cb14-69"><a href="#cb14-69" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"transform"</span><span class="fu">:</span> <span class="st">"None"</span><span class="fu">,</span></span>
<span id="cb14-70"><a href="#cb14-70" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"lower"</span><span class="fu">:</span> <span class="fl">0.0</span><span class="fu">,</span></span>
<span id="cb14-71"><a href="#cb14-71" aria-hidden="true" tabindex="-1"></a>            <span class="dt">"upper"</span><span class="fu">:</span> <span class="fl">1.0</span><span class="fu">}</span></span>
<span id="cb14-72"><a href="#cb14-72" aria-hidden="true" tabindex="-1"></a>    <span class="fu">}</span></span>
<span id="cb14-73"><a href="#cb14-73" aria-hidden="true" tabindex="-1"></a><span class="fu">}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
</section>
<section id="sec-modification-of-hyperparameters" class="level3" data-number="13.5.3">
<h3 data-number="13.5.3" class="anchored" data-anchor-id="sec-modification-of-hyperparameters"><span class="header-section-number">13.5.3</span> Modifying the Hyperparameters</h3>
<p>Ray tune <span class="citation" data-cites="pyto23a">(<a href="references.html#ref-pyto23a" role="doc-biblioref">PyTorch 2023a</a>)</span> does not provide a way to change the specified hyperparameters without re-compilation. However, <code>spotPython</code> provides functions for modifying the hyperparameters, their bounds and factors as well as for activating and de-activating hyperparameters without re-compilation of the Python source code. These functions are described in the following.</p>
<section id="sec-modification-of-default-values" class="level4" data-number="13.5.3.1">
<h4 data-number="13.5.3.1" class="anchored" data-anchor-id="sec-modification-of-default-values"><span class="header-section-number">13.5.3.1</span> Modify <code>hyper_dict</code> Hyperparameters for the Selected Algorithm aka <code>core_model</code></h4>
<p>After specifying the model, the corresponding hyperparameters, their types and bounds are loaded from the <code>JSON</code> file <code>torch_hyper_dict.json</code>. After loading, the user can modify the hyperparameters, e.g., the bounds. <code>spotPython</code> provides a simple rule for de-activating hyperparameters: If the lower and the upper bound are set to identical values, the hyperparameter is de-activated. This is useful for the hyperparameter tuning, because it allows to specify a hyperparameter in the <code>JSON</code> file, but to de-activate it in the <code>fun_control</code> dictionary. This is done in the next step.</p>
</section>
<section id="modify-hyperparameters-of-type-numeric-and-integer-boolean" class="level4" data-number="13.5.3.2">
<h4 data-number="13.5.3.2" class="anchored" data-anchor-id="modify-hyperparameters-of-type-numeric-and-integer-boolean"><span class="header-section-number">13.5.3.2</span> Modify Hyperparameters of Type numeric and integer (boolean)</h4>
<p>Since the hyperparameter <code>k_folds</code> is not used in the <code>PyTorch</code> tutorial, it is de-activated here by setting the lower and upper bound to the same value. Note, <code>k_folds</code> is of type “integer”.</p>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> spotPython.hyperparameters.values <span class="im">import</span> modify_hyper_parameter_bounds</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>fun_control <span class="op">=</span> modify_hyper_parameter_bounds(fun_control, </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"batch_size"</span>, bounds<span class="op">=</span>[<span class="dv">1</span>, <span class="dv">5</span>])</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>fun_control <span class="op">=</span> modify_hyper_parameter_bounds(fun_control, </span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"k_folds"</span>, bounds<span class="op">=</span>[<span class="dv">0</span>, <span class="dv">0</span>])</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>fun_control <span class="op">=</span> modify_hyper_parameter_bounds(fun_control, </span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"patience"</span>, bounds<span class="op">=</span>[<span class="dv">3</span>, <span class="dv">3</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="modify-hyperparameter-of-type-factor" class="level4" data-number="13.5.3.3">
<h4 data-number="13.5.3.3" class="anchored" data-anchor-id="modify-hyperparameter-of-type-factor"><span class="header-section-number">13.5.3.3</span> Modify Hyperparameter of Type factor</h4>
<p>In a similar manner as for the numerical hyperparameters, the categorical hyperparameters can be modified. New configurations can be chosen by adding or deleting levels. For example, the hyperparameter <code>optimizer</code> can be re-configured as follows:</p>
<p>In the following setting, two optimizers (<code>"SGD"</code> and <code>"Adam"</code>) will be compared during the <code>spotPython</code> hyperparameter tuning. The hyperparameter <code>optimizer</code> is active.</p>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> spotPython.hyperparameters.values <span class="im">import</span> modify_hyper_parameter_levels</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>fun_control <span class="op">=</span> modify_hyper_parameter_levels(fun_control,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>     <span class="st">"optimizer"</span>, [<span class="st">"SGD"</span>, <span class="st">"Adam"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The hyperparameter <code>optimizer</code> can be de-activated by choosing only one value (level), here: <code>"SGD"</code>.</p>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>fun_control <span class="op">=</span> modify_hyper_parameter_levels(fun_control, <span class="st">"optimizer"</span>, [<span class="st">"SGD"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As discussed in <a href="#sec-optimizers"><span>Section&nbsp;13.6</span></a>, there are some issues with the LBFGS optimizer. Therefore, the usage of the LBFGS optimizer is not deactivated in <code>spotPython</code> by default. However, the LBFGS optimizer can be activated by adding it to the list of optimizers. <code>Rprop</code> was removed, because it does perform very poorly (as some pre-tests have shown). However, it can also be activated by adding it to the list of optimizers. Since <code>SparseAdam</code> does not support dense gradients, <code>Adam</code> was used instead. Therefore, there are 10 default optimizers:</p>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>fun_control <span class="op">=</span> modify_hyper_parameter_levels(fun_control, <span class="st">"optimizer"</span>,</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"Adadelta"</span>, <span class="st">"Adagrad"</span>, <span class="st">"Adam"</span>, <span class="st">"AdamW"</span>, <span class="st">"Adamax"</span>, <span class="st">"ASGD"</span>, </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"NAdam"</span>, <span class="st">"RAdam"</span>, <span class="st">"RMSprop"</span>, <span class="st">"SGD"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="sec-optimizers" class="level2" data-number="13.6">
<h2 data-number="13.6" class="anchored" data-anchor-id="sec-optimizers"><span class="header-section-number">13.6</span> Optimizers</h2>
<p><a href="24_spot_torch_regression.html#tbl-optimizers">Table&nbsp;<span>14.1</span></a> shows some of the optimizers available in <code>PyTorch</code>:</p>
<p><span class="math inline">\(a\)</span> denotes (0.9,0.999), <span class="math inline">\(b\)</span> (0.5,1.2), and <span class="math inline">\(c\)</span> (1e-6, 50), respectively. <span class="math inline">\(R\)</span> denotes <code>required, but unspecified</code>. “m” denotes <code>momentum</code>, “w_d” <code>weight_decay</code>, “d” <code>dampening</code>, “n” <code>nesterov</code>, “r” <code>rho</code>, “l_s” <code>learning rate for scaling delta</code>, “l_d” <code>lr_decay</code>, “b” <code>betas</code>, “l” <code>lambd</code>, “a” <code>alpha</code>, “m_d” for <code>momentum_decay</code>, “e” <code>etas</code>, and “s_s” for <code>step_sizes</code>.</p>
<div id="tbl-optimizers" class="anchored">
<table class="table">
<caption>Table&nbsp;13.1: Optimizers available in PyTorch (selection). The default values are shown in the table.</caption>
<colgroup>
<col style="width: 20%">
<col style="width: 7%">
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Optimizer</th>
<th style="text-align: left;">lr</th>
<th style="text-align: left;">m</th>
<th style="text-align: left;">w_d</th>
<th style="text-align: left;">d</th>
<th style="text-align: left;">n</th>
<th style="text-align: left;">r</th>
<th style="text-align: left;">l_s</th>
<th style="text-align: left;">l_d</th>
<th style="text-align: left;">b</th>
<th style="text-align: left;">l</th>
<th style="text-align: left;">a</th>
<th style="text-align: left;">m_d</th>
<th style="text-align: left;">e</th>
<th style="text-align: left;">s_s</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Adadelta</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">0.</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">0.9</td>
<td style="text-align: left;">1.</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="even">
<td style="text-align: left;">Adagrad</td>
<td style="text-align: left;">1e-2</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">0.</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">0.</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Adam</td>
<td style="text-align: left;">1e-3</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">0.</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;"><span class="math inline">\(a\)</span></td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="even">
<td style="text-align: left;">AdamW</td>
<td style="text-align: left;">1e-3</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">1e-2</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;"><span class="math inline">\(a\)</span></td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SparseAdam</td>
<td style="text-align: left;">1e-3</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;"><span class="math inline">\(a\)</span></td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="even">
<td style="text-align: left;">Adamax</td>
<td style="text-align: left;">2e-3</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">0.</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;"><span class="math inline">\(a\)</span></td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ASGD</td>
<td style="text-align: left;">1e-2</td>
<td style="text-align: left;">.9</td>
<td style="text-align: left;">0.</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">F</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">1e-4</td>
<td style="text-align: left;">.75</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="even">
<td style="text-align: left;">LBFGS</td>
<td style="text-align: left;">1.</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NAdam</td>
<td style="text-align: left;">2e-3</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">0.</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;"><span class="math inline">\(a\)</span></td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">0</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="even">
<td style="text-align: left;">RAdam</td>
<td style="text-align: left;">1e-3</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">0.</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;"><span class="math inline">\(a\)</span></td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RMSprop</td>
<td style="text-align: left;">1e-2</td>
<td style="text-align: left;">0.</td>
<td style="text-align: left;">0.</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;"><span class="math inline">\(a\)</span></td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rprop</td>
<td style="text-align: left;">1e-2</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;"><span class="math inline">\(b\)</span></td>
<td style="text-align: left;"><span class="math inline">\(c\)</span></td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SGD</td>
<td style="text-align: left;"><span class="math inline">\(R\)</span></td>
<td style="text-align: left;">0.</td>
<td style="text-align: left;">0.</td>
<td style="text-align: left;">0.</td>
<td style="text-align: left;">F</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
<td style="text-align: left;">-</td>
</tr>
</tbody>
</table>
</div>
<p><code>spotPython</code> implements an <code>optimization</code> handler that maps the optimizer names to the corresponding <code>PyTorch</code> optimizers.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
A note on LBFGS
</div>
</div>
<div class="callout-body-container callout-body">
<p>We recommend deactivating <code>PyTorch</code>’s LBFGS optimizer, because it does not perform very well. The <code>PyTorch</code> documentation, see <a href="https://pytorch.org/docs/stable/generated/torch.optim.LBFGS.html#torch.optim.LBFGS">https://pytorch.org/docs/stable/generated/torch.optim.LBFGS.html#torch.optim.LBFGS</a>, states:</p>
<blockquote class="blockquote">
<p>This is a very memory intensive optimizer (it requires additional <code>param_bytes * (history_size + 1)</code> bytes). If it doesn’t fit in memory try reducing the history size, or use a different algorithm.</p>
</blockquote>
<p>Furthermore, the LBFGS optimizer is not compatible with the <code>PyTorch</code> tutorial. The reason is that the LBFGS optimizer requires the <code>closure</code> function, which is not implemented in the <code>PyTorch</code> tutorial. Therefore, the <code>LBFGS</code> optimizer is recommended here. Since there are ten optimizers in the portfolio, it is not recommended tuning the hyperparameters that effect one single optimizer only.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
A note on the learning rate
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>spotPython</code> provides a multiplier for the default learning rates, <code>lr_mult</code>, because optimizers use different learning rates. Using a multiplier for the learning rates might enable a simultaneous tuning of the learning rates for all optimizers. However, this is not recommended, because the learning rates are not comparable across optimizers. Therefore, we recommend fixing the learning rate for all optimizers if multiple optimizers are used. This can be done by setting the lower and upper bounds of the learning rate multiplier to the same value as shown below.</p>
<p>Thus, the learning rate, which affects the <code>SGD</code> optimizer, will be set to a fixed value. We choose the default value of <code>1e-3</code> for the learning rate, because it is used in other <code>PyTorch</code> examples (it is also the default value used by <code>spotPython</code> as defined in the <code>optimizer_handler()</code> method). We recommend tuning the learning rate later, when a reduced set of optimizers is fixed. Here, we will demonstrate how to select in a screening phase the optimizers that should be used for the hyperparameter tuning.</p>
</div>
</div>
<p>For the same reason, we will fix the <code>sgd_momentum</code> to <code>0.9</code>.</p>
<div class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>fun_control <span class="op">=</span> modify_hyper_parameter_bounds(fun_control,</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"lr_mult"</span>, bounds<span class="op">=</span>[<span class="fl">1.0</span>, <span class="fl">1.0</span>])</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>fun_control <span class="op">=</span> modify_hyper_parameter_bounds(fun_control,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"sgd_momentum"</span>, bounds<span class="op">=</span>[<span class="fl">0.9</span>, <span class="fl">0.9</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="sec-data-splitting" class="level2" data-number="13.7">
<h2 data-number="13.7" class="anchored" data-anchor-id="sec-data-splitting"><span class="header-section-number">13.7</span> Evaluation: Data Splitting</h2>
<p>The evaluation procedure requires the specification of the way how the data is split into a train and a test set and the loss function (and a metric). As a default, <code>spotPython</code> provides a standard hold-out data split and cross validation.</p>
<section id="hold-out-data-split" class="level3" data-number="13.7.1">
<h3 data-number="13.7.1" class="anchored" data-anchor-id="hold-out-data-split"><span class="header-section-number">13.7.1</span> Hold-out Data Split</h3>
<p>If a hold-out data split is used, the data will be partitioned into a training, a validation, and a test data set. The split depends on the setting of the <code>eval</code> parameter. If <code>eval</code> is set to <code>train_hold_out</code>, one data set, usually the original training data set, is split into a new training and a validation data set. The training data set is used for training the model. The validation data set is used for the evaluation of the hyperparameter configuration and early stopping to prevent overfitting. In this case, the original test data set is not used.</p>
<p><code>spotPython</code> returns the hyperparameters of the machine learning and deep learning models, e.g., number of layers, learning rate, or optimizer, but not the model weights. Therefore, after the SPOT run is finished, the corresponding model with the optimized architecture has to be trained again with the best hyperparameter configuration. The training is performed on the training data set. The test data set is used for the final evaluation of the model.</p>
<p>Summarizing, the following splits are performed in the hold-out setting:</p>
<ol type="1">
<li>Run <code>spotPython</code> with <code>eval</code> set to <code>train_hold_out</code> to determine the best hyperparameter configuration.</li>
<li>Train the model with the best hyperparameter configuration (“architecture”) on the training data set: <code>train_tuned(model_spot, train, "model_spot.pt")</code>.</li>
<li>Test the model on the test data: <code>test_tuned(model_spot, test, "model_spot.pt")</code></li>
</ol>
<p>These steps will be exemplified in the following sections. In addition to this <code>hold-out</code> setting, <code>spotPython</code> provides another hold-out setting, where an explicit test data is specified by the user that will be used as the validation set. To choose this option, the <code>eval</code> parameter is set to <code>test_hold_out</code>. In this case, the training data set is used for the model training. Then, the explicitly defined test data set is used for the evaluation of the hyperparameter configuration (the validation).</p>
</section>
<section id="cross-validation" class="level3" data-number="13.7.2">
<h3 data-number="13.7.2" class="anchored" data-anchor-id="cross-validation"><span class="header-section-number">13.7.2</span> Cross-Validation</h3>
<p>The cross validation setting is used by setting the <code>eval</code> parameter to <code>train_cv</code> or <code>test_cv</code>. In both cases, the data set is split into <span class="math inline">\(k\)</span> folds. The model is trained on <span class="math inline">\(k-1\)</span> folds and evaluated on the remaining fold. This is repeated <span class="math inline">\(k\)</span> times, so that each fold is used exactly once for evaluation. The final evaluation is performed on the test data set. The cross validation setting is useful for small data sets, because it allows to use all data for training and evaluation. However, it is computationally expensive, because the model has to be trained <span class="math inline">\(k\)</span> times.</p>
<p>Combinations of the above settings are possible, e.g., cross validation can be used for training and hold-out for evaluation or <em>vice versa</em>. Also, cross validation can be used for training and testing. Because cross validation is not used in the <code>PyTorch</code> tutorial <span class="citation" data-cites="pyto23a">(<a href="references.html#ref-pyto23a" role="doc-biblioref">PyTorch 2023a</a>)</span>, it is not considered further here.</p>
</section>
<section id="overview-of-the-evaluation-settings" class="level3" data-number="13.7.3">
<h3 data-number="13.7.3" class="anchored" data-anchor-id="overview-of-the-evaluation-settings"><span class="header-section-number">13.7.3</span> Overview of the Evaluation Settings</h3>
<section id="settings-for-the-hyperparameter-tuning" class="level4" data-number="13.7.3.1">
<h4 data-number="13.7.3.1" class="anchored" data-anchor-id="settings-for-the-hyperparameter-tuning"><span class="header-section-number">13.7.3.1</span> Settings for the Hyperparameter Tuning</h4>
<p>An overview of the training evaluations is shown in <a href="24_spot_torch_regression.html#tbl-eval-settings">Table&nbsp;<span>14.2</span></a>. <code>"train_cv"</code> and <code>"test_cv"</code> use <code>sklearn.model_selection.KFold()</code> internally. More details on the data splitting are provided in <a href="99_spot_doc.html#sec-detailed-data-splitting"><span>Section&nbsp;15.14</span></a> (in the Appendix).</p>
<div id="tbl-eval-settings" class="anchored">
<table class="table">
<caption>Table&nbsp;13.2: Overview of the evaluation settings.</caption>
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 28%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th><code>eval</code></th>
<th style="text-align: center;"><code>train</code></th>
<th style="text-align: center;"><code>test</code></th>
<th style="text-align: left;">function</th>
<th style="text-align: left;">comment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>"train_hold_out"</code></td>
<td style="text-align: center;"><span class="math inline">\(\checkmark\)</span></td>
<td style="text-align: center;"></td>
<td style="text-align: left;"><code>train_one_epoch()</code>, <code>validate_one_epoch()</code> for early stopping</td>
<td style="text-align: left;">splits the <code>train</code> data set internally</td>
</tr>
<tr class="even">
<td><code>"test_hold_out"</code></td>
<td style="text-align: center;"><span class="math inline">\(\checkmark\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\checkmark\)</span></td>
<td style="text-align: left;"><code>train_one_epoch()</code>, <code>validate_one_epoch()</code> for early stopping</td>
<td style="text-align: left;">use the <code>test data set</code> for <code>validate_one_epoch()</code></td>
</tr>
<tr class="odd">
<td><code>"train_cv"</code></td>
<td style="text-align: center;"><span class="math inline">\(\checkmark\)</span></td>
<td style="text-align: center;"></td>
<td style="text-align: left;"><code>evaluate_cv(net, train)</code></td>
<td style="text-align: left;">CV using the <code>train</code> data set</td>
</tr>
<tr class="even">
<td><code>"test_cv"</code></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\(\checkmark\)</span></td>
<td style="text-align: left;"><code>evaluate_cv(net, test)</code></td>
<td style="text-align: left;">CV using the <code>test</code> data set . Identical to <code>"train_cv"</code>, uses only test data.</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="settings-for-the-final-evaluation-of-the-tuned-architecture" class="level4" data-number="13.7.3.2">
<h4 data-number="13.7.3.2" class="anchored" data-anchor-id="settings-for-the-final-evaluation-of-the-tuned-architecture"><span class="header-section-number">13.7.3.2</span> Settings for the Final Evaluation of the Tuned Architecture</h4>
<section id="training-of-the-tuned-architecture" class="level5" data-number="13.7.3.2.1">
<h5 data-number="13.7.3.2.1" class="anchored" data-anchor-id="training-of-the-tuned-architecture"><span class="header-section-number">13.7.3.2.1</span> Training of the Tuned Architecture</h5>
<p><code>train_tuned(model, train)</code>: train the model with the best hyperparameter configuration (or simply the default) on the training data set. It splits the <code>train</code>data into new <code>train</code> and <code>validation</code> sets using <code>create_train_val_data_loaders()</code>, which calls <code>torch.utils.data.random_split()</code> internally. Currently, 60% of the data is used for training and 40% for validation. The <code>train</code> data is used for training the model with <code>train_hold_out()</code>. The <code>validation</code> data is used for early stopping using <code>validate_fold_or_hold_out()</code> on the <code>validation</code> data set.</p>
</section>
<section id="testing-of-the-tuned-architecture" class="level5" data-number="13.7.3.2.2">
<h5 data-number="13.7.3.2.2" class="anchored" data-anchor-id="testing-of-the-tuned-architecture"><span class="header-section-number">13.7.3.2.2</span> Testing of the Tuned Architecture</h5>
<p><code>test_tuned(model, test)</code>: test the model on the test data set. No data splitting is performed. The (trained) model is evaluated using the <code>validate_fold_or_hold_out()</code> function. Note: During training, <code>shuffle</code> is set to <code>True</code>, whereas during testing, <code>shuffle</code> is set to <code>False</code>.</p>
<p><a href="99_spot_doc.html#sec-final-model-evaluation"><span>Section&nbsp;15.14.1.4</span></a> describes the final evaluation of the tuned architecture.</p>
</section>
</section>
</section>
</section>
<section id="sec-loss-functions" class="level2" data-number="13.8">
<h2 data-number="13.8" class="anchored" data-anchor-id="sec-loss-functions"><span class="header-section-number">13.8</span> Evaluation: Loss Functions and Metrics</h2>
<p>The key <code>"loss_function"</code> specifies the loss function which is used during the optimization. There are several different loss functions under <code>PyTorch</code>’s <code>nn</code> package. For example, a simple loss is <code>MSELoss</code>, which computes the mean-squared error between the output and the target. In this tutorial we will use <code>CrossEntropyLoss</code>, because it is also used in the <code>PyTorch</code> tutorial.</p>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> torch.nn <span class="im">import</span> CrossEntropyLoss</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>loss_function <span class="op">=</span> CrossEntropyLoss()</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>fun_control.update({<span class="st">"loss_function"</span>: loss_function})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In addition to the loss functions, <code>spotPython</code> provides access to a large number of metrics.</p>
<ul>
<li>The key <code>"metric_sklearn"</code> is used for metrics that follow the <code>scikit-learn</code> conventions.</li>
<li>The key <code>"river_metric"</code> is used for the river based evaluation <span class="citation" data-cites="mont20a">(<a href="references.html#ref-mont20a" role="doc-biblioref">Montiel et al. 2021</a>)</span> via <code>eval_oml_iter_progressive</code>, and</li>
<li>the key <code>"metric_torch"</code> is used for the metrics from <code>TorchMetrics</code>.</li>
</ul>
<p><code>TorchMetrics</code> is a collection of more than 90 PyTorch metrics, see <a href="https://torchmetrics.readthedocs.io/en/latest/">https://torchmetrics.readthedocs.io/en/latest/</a>. Because the <code>PyTorch</code> tutorial uses the accuracy as metric, we use the same metric here. Currently, accuracy is computed in the tutorial’s example code. We will use <code>TorchMetrics</code> instead, because it offers more flexibilty, e.g., it can be used for regression and classification. Furthermore, <code>TorchMetrics</code> offers the following advantages:</p>
<pre><code>* A standardized interface to increase reproducibility
* Reduces Boilerplate
* Distributed-training compatible
* Rigorously tested
* Automatic accumulation over batches
* Automatic synchronization between multiple devices</code></pre>
<p>Therefore, we set</p>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torchmetrics</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>metric_torch <span class="op">=</span> torchmetrics.Accuracy(task<span class="op">=</span><span class="st">"multiclass"</span>, num_classes<span class="op">=</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>loss_function <span class="op">=</span> CrossEntropyLoss()</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>weights <span class="op">=</span> <span class="fl">1.0</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>metric_torch <span class="op">=</span> torchmetrics.Accuracy(task<span class="op">=</span><span class="st">"multiclass"</span>, num_classes<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>shuffle <span class="op">=</span> <span class="va">True</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="bu">eval</span> <span class="op">=</span> <span class="st">"train_hold_out"</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>device <span class="op">=</span> DEVICE</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>show_batch_interval <span class="op">=</span> <span class="dv">100_000</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>path<span class="op">=</span><span class="st">"torch_model.pt"</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>fun_control.update({</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>               <span class="st">"data_dir"</span>: <span class="va">None</span>,</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>               <span class="st">"checkpoint_dir"</span>: <span class="va">None</span>,</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>               <span class="st">"horizon"</span>: <span class="va">None</span>,</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>               <span class="st">"oml_grace_period"</span>: <span class="va">None</span>,</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>               <span class="st">"weights"</span>: weights,</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>               <span class="st">"step"</span>: <span class="va">None</span>,</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>               <span class="st">"log_level"</span>: <span class="dv">50</span>,</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>               <span class="st">"weight_coeff"</span>: <span class="va">None</span>,</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>               <span class="st">"metric_torch"</span>: metric_torch,</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>               <span class="st">"metric_river"</span>: <span class="va">None</span>,</span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>               <span class="st">"metric_sklearn"</span>: <span class="va">None</span>,</span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a>               <span class="st">"loss_function"</span>: loss_function,</span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a>               <span class="st">"shuffle"</span>: shuffle,</span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a>               <span class="st">"eval"</span>: <span class="bu">eval</span>,</span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a>               <span class="st">"device"</span>: device,</span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a>               <span class="st">"show_batch_interval"</span>: show_batch_interval,</span>
<span id="cb23-27"><a href="#cb23-27" aria-hidden="true" tabindex="-1"></a>               <span class="st">"path"</span>: path,</span>
<span id="cb23-28"><a href="#cb23-28" aria-hidden="true" tabindex="-1"></a>               })</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="sec-prepare-spot-call" class="level2" data-number="13.9">
<h2 data-number="13.9" class="anchored" data-anchor-id="sec-prepare-spot-call"><span class="header-section-number">13.9</span> Preparing the SPOT Call</h2>
<p>The following code passes the information about the parameter ranges and bounds to <code>spot</code>.</p>
<p>Now, the dictionary <code>fun_control</code> contains all information needed for the hyperparameter tuning. Before the hyperparameter tuning is started, it is recommended to take a look at the experimental design. The method <code>gen_design_table</code> generates a design table as follows:</p>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> spotPython.utils.eda <span class="im">import</span> gen_design_table</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(gen_design_table(fun_control))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This allows to check if all information is available and if the information is correct. <a href="24_spot_torch_regression.html#tbl-design">Table&nbsp;<span>14.3</span></a> shows the experimental design for the hyperparameter tuning. The table shows the hyperparameters, their types, default values, lower and upper bounds, and the transformation function. The transformation function is used to transform the hyperparameter values from the unit hypercube to the original domain. The transformation function is applied to the hyperparameter values before the evaluation of the objective function. Hyperparameter transformations are shown in the column “transform”, e.g., the <code>l1</code> default is <code>5</code>, which results in the value <span class="math inline">\(2^5 = 32\)</span> for the network, because the transformation <code>transform_power_2_int</code> was selected in the <code>JSON</code> file. The default value of the <code>batch_size</code> is set to <code>4</code>, which results in a batch size of <span class="math inline">\(2^4 = 16\)</span>.</p>
<div id="tbl-design" class="anchored">
<table class="table">
<caption>Table&nbsp;13.3: Experimental design for the hyperparameter tuning.</caption>
<colgroup>
<col style="width: 17%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>name</th>
<th>type</th>
<th>default</th>
<th>lower</th>
<th>upper</th>
<th>transform</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>l1</td>
<td>int</td>
<td>5</td>
<td>2</td>
<td>9</td>
<td>transform_power_2_int</td>
</tr>
<tr class="even">
<td>l2</td>
<td>int</td>
<td>5</td>
<td>2</td>
<td>9</td>
<td>transform_power_2_int</td>
</tr>
<tr class="odd">
<td>lr_mult</td>
<td>float</td>
<td>1.0</td>
<td>1</td>
<td>1</td>
<td>None</td>
</tr>
<tr class="even">
<td>batch_size</td>
<td>int</td>
<td>4</td>
<td>1</td>
<td>5</td>
<td>transform_power_2_int</td>
</tr>
<tr class="odd">
<td>epochs</td>
<td>int</td>
<td>3</td>
<td>3</td>
<td>4</td>
<td>transform_power_2_int</td>
</tr>
<tr class="even">
<td>k_folds</td>
<td>int</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>None</td>
</tr>
<tr class="odd">
<td>patience</td>
<td>int</td>
<td>5</td>
<td>3</td>
<td>3</td>
<td>None</td>
</tr>
<tr class="even">
<td>optimizer</td>
<td>factor</td>
<td>SGD</td>
<td>0</td>
<td>9</td>
<td>None</td>
</tr>
<tr class="odd">
<td>sgd_momentum</td>
<td>float</td>
<td>0.0</td>
<td>0.9</td>
<td>0.9</td>
<td>None</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="sec-the-objective-function" class="level2" data-number="13.10">
<h2 data-number="13.10" class="anchored" data-anchor-id="sec-the-objective-function"><span class="header-section-number">13.10</span> The Objective Function <code>fun_torch</code></h2>
<p>The objective function <code>fun_torch</code> is selected next. It implements an interface from <code>PyTorch</code>’s training, validation, and testing methods to <code>spotPython</code>.</p>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> spotPython.fun.hypertorch <span class="im">import</span> HyperTorch</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>fun <span class="op">=</span> HyperTorch().fun_torch</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="sec-default-hyperparameters" class="level2" data-number="13.11">
<h2 data-number="13.11" class="anchored" data-anchor-id="sec-default-hyperparameters"><span class="header-section-number">13.11</span> Using Default Hyperparameters or Results from Previous Runs</h2>
<p>We add the default setting to the initial design:</p>
<div class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> spotPython.hyperparameters.values <span class="im">import</span> get_default_hyperparameters_as_array</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>hyper_dict<span class="op">=</span>TorchHyperDict().load()</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>X_start <span class="op">=</span> get_default_hyperparameters_as_array(fun_control, hyper_dict)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="sec-call-the-hyperparameter-tuner" class="level2" data-number="13.12">
<h2 data-number="13.12" class="anchored" data-anchor-id="sec-call-the-hyperparameter-tuner"><span class="header-section-number">13.12</span> Starting the Hyperparameter Tuning</h2>
<p>The <code>spotPython</code> hyperparameter tuning is started by calling the <code>Spot</code> function. Here, we will run the tuner for approximately 30 minutes (<code>max_time</code>). Note: the initial design is always evaluated in the <code>spotPython</code> run. As a consequence, the run may take longer than specified by <code>max_time</code>, because the evaluation time of initial design (here: <code>init_size</code>, 10 points) is performed independently of <code>max_time</code>.</p>
<div class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> spotPython.spot <span class="im">import</span> spot</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> math <span class="im">import</span> inf</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>spot_tuner <span class="op">=</span> spot.Spot(fun<span class="op">=</span>fun,</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>                   lower <span class="op">=</span> lower,</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>                   upper <span class="op">=</span> upper,</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>                   fun_evals <span class="op">=</span> inf,</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>                   fun_repeats <span class="op">=</span> <span class="dv">1</span>,</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>                   max_time <span class="op">=</span> MAX_TIME,</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>                   noise <span class="op">=</span> <span class="va">False</span>,</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>                   tolerance_x <span class="op">=</span> np.sqrt(np.spacing(<span class="dv">1</span>)),</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>                   var_type <span class="op">=</span> var_type,</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>                   var_name <span class="op">=</span> var_name,</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>                   infill_criterion <span class="op">=</span> <span class="st">"y"</span>,</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>                   n_points <span class="op">=</span> <span class="dv">1</span>,</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>                   seed<span class="op">=</span><span class="dv">123</span>,</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>                   log_level <span class="op">=</span> <span class="dv">50</span>,</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a>                   show_models<span class="op">=</span> <span class="va">False</span>,</span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>                   show_progress<span class="op">=</span> <span class="va">True</span>,</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>                   fun_control <span class="op">=</span> fun_control,</span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>                   design_control<span class="op">=</span>{<span class="st">"init_size"</span>: INIT_SIZE,</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>                                   <span class="st">"repeats"</span>: <span class="dv">1</span>},</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>                   surrogate_control<span class="op">=</span>{<span class="st">"noise"</span>: <span class="va">True</span>,</span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"cod_type"</span>: <span class="st">"norm"</span>,</span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"min_theta"</span>: <span class="op">-</span><span class="dv">4</span>,</span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"max_theta"</span>: <span class="dv">3</span>,</span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"n_theta"</span>: <span class="bu">len</span>(var_name),</span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"model_fun_evals"</span>: <span class="dv">10_000</span>,</span>
<span id="cb27-29"><a href="#cb27-29" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">"log_level"</span>: <span class="dv">50</span></span>
<span id="cb27-30"><a href="#cb27-30" aria-hidden="true" tabindex="-1"></a>                                      })</span>
<span id="cb27-31"><a href="#cb27-31" aria-hidden="true" tabindex="-1"></a>spot_tuner.run(X_start<span class="op">=</span>X_start)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>During the run, the following output is shown:</p>
<pre class="{raw}"><code>config: {'l1': 128, 'l2': 8, 'lr_mult': 1.0, 'batch_size': 32,
    'epochs': 16, 'k_folds': 0, 'patience': 3,
    'optimizer': 'AdamW', 'sgd_momentum': 0.9}
Epoch: 1
Loss on hold-out set: 1.5143253986358642
Accuracy on hold-out set: 0.4447
MulticlassAccuracy value on hold-out data: 0.4447000026702881
Epoch: 2
...
Epoch: 15
Loss on hold-out set: 1.2061678514480592
Accuracy on hold-out set: 0.59505
MulticlassAccuracy value on hold-out data: 0.5950499773025513
Early stopping at epoch 14
Returned to Spot: Validation loss: 1.2061678514480592
----------------------------------------------</code></pre>
</section>
<section id="sec-tensorboard" class="level2" data-number="13.13">
<h2 data-number="13.13" class="anchored" data-anchor-id="sec-tensorboard"><span class="header-section-number">13.13</span> Tensorboard</h2>
<p>The textual output shown in the console (or code cell) can be visualized with Tensorboard.</p>
<section id="tensorboard-start-tensorboard" class="level3" data-number="13.13.1">
<h3 data-number="13.13.1" class="anchored" data-anchor-id="tensorboard-start-tensorboard"><span class="header-section-number">13.13.1</span> Tensorboard: Start Tensorboard</h3>
<p>Start TensorBoard through the command line to visualize data you logged. Specify the root log directory as used in <code>fun_control = fun_control_init(task="regression", tensorboard_path="runs/24_spot_torch_regression")</code> as the <code>tensorboard_path</code>. The argument logdir points to directory where TensorBoard will look to find event files that it can display. TensorBoard will recursively walk the directory structure rooted at logdir, looking for .<em>tfevents.</em> files.</p>
<pre class="{raw}"><code>tensorboard --logdir=runs</code></pre>
<p>Go to the URL it provides or to <a href="http://localhost:6006/">http://localhost:6006/</a>. The following figures show some screenshots of Tensorboard.</p>
<div id="fig-tensorboard_0" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="./figures/14-torch_p040025_10min_5init_2023-06-07_12-41-06_tensorboard_01.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;13.1: Tensorboard</figcaption>
</figure>
</div>
<div id="fig-tensorboard_hdparams" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="./figures/14-torch_p040025_10min_5init_2023-06-07_12-41-06_tensorboard_02.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;13.2: Tensorboard</figcaption>
</figure>
</div>
</section>
<section id="sec-saving-the-state-of-the-notebook" class="level3" data-number="13.13.2">
<h3 data-number="13.13.2" class="anchored" data-anchor-id="sec-saving-the-state-of-the-notebook"><span class="header-section-number">13.13.2</span> Saving the State of the Notebook</h3>
<p>The state of the notebook can be saved and reloaded as follows:</p>
<div class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pickle</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>SAVE <span class="op">=</span> <span class="va">False</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>LOAD <span class="op">=</span> <span class="va">False</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> SAVE:</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>    result_file_name <span class="op">=</span> <span class="st">"res_"</span> <span class="op">+</span> experiment_name <span class="op">+</span> <span class="st">".pkl"</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> <span class="bu">open</span>(result_file_name, <span class="st">'wb'</span>) <span class="im">as</span> f:</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>        pickle.dump(spot_tuner, f)</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> LOAD:</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>    result_file_name <span class="op">=</span> <span class="st">"add_the_name_of_the_result_file_here.pkl"</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> <span class="bu">open</span>(result_file_name, <span class="st">'rb'</span>) <span class="im">as</span> f:</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>        spot_tuner <span class="op">=</span>  pickle.load(f)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="sec-results" class="level2" data-number="13.14">
<h2 data-number="13.14" class="anchored" data-anchor-id="sec-results"><span class="header-section-number">13.14</span> Results</h2>
<p>After the hyperparameter tuning run is finished, the progress of the hyperparameter tuning can be visualized. The following code generates the progress plot from <a href="24_spot_torch_regression.html#fig-progress">Figure&nbsp;<span>14.4</span></a>.</p>
<div class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>spot_tuner.plot_progress(log_y<span class="op">=</span><span class="va">False</span>, </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>    filename<span class="op">=</span><span class="st">"./figures/"</span> <span class="op">+</span> experiment_name<span class="op">+</span><span class="st">"_progress.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="fig-progress" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="./figures/figures14-torch_maans03_60min_10init_2023-05-19_16-34-33_progress.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;13.3: Progress plot. <code>Black</code> dots denote results from the initial design. <code>Red</code> dots illustrate the improvement found by the surrogate model based optimization (surrogate model based optimization).</figcaption>
</figure>
</div>
<p><a href="24_spot_torch_regression.html#fig-progress">Figure&nbsp;<span>14.4</span></a> shows a typical behaviour that can be observed in many hyperparameter studies <span class="citation" data-cites="bart21i">(<a href="references.html#ref-bart21i" role="doc-biblioref">Bartz et al. 2022</a>)</span>: the largest improvement is obtained during the evaluation of the initial design. The surrogate model based optimization-optimization with the surrogate refines the results. <a href="24_spot_torch_regression.html#fig-progress">Figure&nbsp;<span>14.4</span></a> also illustrates one major difference between <code>ray[tune]</code> as used in <span class="citation" data-cites="pyto23a">PyTorch (<a href="references.html#ref-pyto23a" role="doc-biblioref">2023a</a>)</span> and <code>spotPython</code>: the <code>ray[tune]</code> uses a random search and will generate results similar to the <em>black</em> dots, whereas <code>spotPython</code> uses a surrogate model based optimization and presents results represented by <em>red</em> dots in <a href="24_spot_torch_regression.html#fig-progress">Figure&nbsp;<span>14.4</span></a>. The surrogate model based optimization is considered to be more efficient than a random search, because the surrogate model guides the search towards promising regions in the hyperparameter space.</p>
<p>In addition to the improved (“optimized”) hyperparameter values, <code>spotPython</code> allows a statistical analysis, e.g., a sensitivity analysis, of the results. We can print the results of the hyperparameter tuning, see <a href="24_spot_torch_regression.html#tbl-results">Table&nbsp;<span>14.4</span></a>. The table shows the hyperparameters, their types, default values, lower and upper bounds, and the transformation function. The column “tuned” shows the tuned values. The column “importance” shows the importance of the hyperparameters. The column “stars” shows the importance of the hyperparameters in stars. The importance is computed by the SPOT software.</p>
<div class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(gen_design_table(fun_control<span class="op">=</span>fun_control, spot<span class="op">=</span>spot_tuner))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="tbl-results" class="anchored">
<table class="table">
<caption>Table&nbsp;13.4: Results of the hyperparameter tuning.</caption>
<colgroup>
<col style="width: 10%">
<col style="width: 7%">
<col style="width: 16%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th>name</th>
<th>type</th>
<th>default</th>
<th style="text-align: right;">lower</th>
<th style="text-align: right;">upper</th>
<th style="text-align: right;">tuned</th>
<th>transform</th>
<th style="text-align: right;">importance</th>
<th>stars</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>l1</td>
<td>int</td>
<td>5</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">9.0</td>
<td style="text-align: right;">7.0</td>
<td>pow_2_int</td>
<td style="text-align: right;">100.00</td>
<td>***</td>
</tr>
<tr class="even">
<td>l2</td>
<td>int</td>
<td>5</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">9.0</td>
<td style="text-align: right;">3.0</td>
<td>pow_2_int</td>
<td style="text-align: right;">96.29</td>
<td>***</td>
</tr>
<tr class="odd">
<td>lr_mult</td>
<td>float</td>
<td>1.0</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">10.0</td>
<td style="text-align: right;">0.1</td>
<td>None</td>
<td style="text-align: right;">0.00</td>
<td></td>
</tr>
<tr class="even">
<td>batchsize</td>
<td>int</td>
<td>4</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">5.0</td>
<td style="text-align: right;">4.0</td>
<td>pow_2_int</td>
<td style="text-align: right;">0.00</td>
<td></td>
</tr>
<tr class="odd">
<td>epochs</td>
<td>int</td>
<td>3</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">4.0</td>
<td>pow_2_int</td>
<td style="text-align: right;">4.18</td>
<td>*</td>
</tr>
<tr class="even">
<td>k_folds</td>
<td>int</td>
<td>2</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.0</td>
<td>None</td>
<td style="text-align: right;">0.00</td>
<td></td>
</tr>
<tr class="odd">
<td>patience</td>
<td>int</td>
<td>5</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">3.0</td>
<td>None</td>
<td style="text-align: right;">0.00</td>
<td></td>
</tr>
<tr class="even">
<td>optimizer</td>
<td>factor</td>
<td>SGD</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">9.0</td>
<td style="text-align: right;">3.0</td>
<td>None</td>
<td style="text-align: right;">0.16</td>
<td>.</td>
</tr>
</tbody>
</table>
</div>
<p>To visualize the most important hyperparameters, <code>spotPython</code> provides the function <code>plot_importance</code>. The following code generates the importance plot from <a href="24_spot_torch_regression.html#fig-importance">Figure&nbsp;<span>14.5</span></a>.</p>
<div class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>spot_tuner.plot_importance(threshold<span class="op">=</span><span class="fl">0.025</span>,</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>    filename<span class="op">=</span><span class="st">"./figures/"</span> <span class="op">+</span> experiment_name<span class="op">+</span><span class="st">"_importance.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="fig-importance" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="./figures/figures14-torch_maans03_60min_10init_2023-05-19_16-34-33_importance.png" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;13.4: Variable importance</figcaption>
</figure>
</div>
<section id="sec-get-spot-results" class="level3" data-number="13.14.1">
<h3 data-number="13.14.1" class="anchored" data-anchor-id="sec-get-spot-results"><span class="header-section-number">13.14.1</span> Get SPOT Results</h3>
<p>The architecture of the <code>spotPython</code> model can be obtained by the following code:</p>
<div class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> spotPython.hyperparameters.values <span class="im">import</span> get_one_core_model_from_X</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> spot_tuner.to_all_dim(spot_tuner.min_X.reshape(<span class="dv">1</span>,<span class="op">-</span><span class="dv">1</span>))</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>model_spot <span class="op">=</span> get_one_core_model_from_X(X, fun_control)</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>model_spot</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>First, the numerical representation of the hyperparameters are obtained, i.e., the numpy array <code>X</code> is generated. This array is then used to generate the model <code>model_spot</code> by the function <code>get_one_core_model_from_X</code>. The model <code>model_spot</code> has the following architecture:</p>
<pre class="{raw}"><code>Net_CIFAR10(
  (conv1): Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
  (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1,
    ceil_mode=False)
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=64, bias=True)
  (fc2): Linear(in_features=64, out_features=32, bias=True)
  (fc3): Linear(in_features=32, out_features=10, bias=True)
)</code></pre>
</section>
<section id="get-default-hyperparameters" class="level3" data-number="13.14.2">
<h3 data-number="13.14.2" class="anchored" data-anchor-id="get-default-hyperparameters"><span class="header-section-number">13.14.2</span> Get Default Hyperparameters</h3>
<p>In a similar manner as in <a href="#sec-get-spot-results"><span>Section&nbsp;13.14.1</span></a>, the default hyperparameters can be obtained.</p>
<div class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fun_control was modified, we generate a new one with the original </span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="co"># default hyperparameters</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> spotPython.hyperparameters.values <span class="im">import</span> get_one_core_model_from_X</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>fc <span class="op">=</span> fun_control</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>fc.update({<span class="st">"core_model_hyper_dict"</span>:</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>    hyper_dict[fun_control[<span class="st">"core_model"</span>].<span class="va">__name__</span>]})</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>model_default <span class="op">=</span> get_one_core_model_from_X(X_start, fun_control<span class="op">=</span>fc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The corresponding default model has the following architecture:</p>
<pre class="{raw}"><code>Net_CIFAR10(
  (conv1): Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
  (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1,
    ceil_mode=False)
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=32, bias=True)
  (fc2): Linear(in_features=32, out_features=32, bias=True)
  (fc3): Linear(in_features=32, out_features=10, bias=True)
)</code></pre>
</section>
<section id="evaluation-of-the-default-architecture" class="level3" data-number="13.14.3">
<h3 data-number="13.14.3" class="anchored" data-anchor-id="evaluation-of-the-default-architecture"><span class="header-section-number">13.14.3</span> Evaluation of the Default Architecture</h3>
<p>The method <code>train_tuned</code> takes a model architecture without trained weights and trains this model with the train data. The train data is split into train and validation data. The validation data is used for early stopping. The trained model weights are saved as a dictionary.</p>
<p>This evaluation is similar to the final evaluation in <span class="citation" data-cites="pyto23a">PyTorch (<a href="references.html#ref-pyto23a" role="doc-biblioref">2023a</a>)</span>.</p>
<div class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> spotPython.torch.traintest <span class="im">import</span> (</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>    train_tuned,</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>    test_tuned,</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>train_tuned(net<span class="op">=</span>model_default, train_dataset<span class="op">=</span>train, shuffle<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>        loss_function<span class="op">=</span>fun_control[<span class="st">"loss_function"</span>],</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>        metric<span class="op">=</span>fun_control[<span class="st">"metric_torch"</span>],</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>        device <span class="op">=</span> DEVICE, show_batch_interval<span class="op">=</span><span class="dv">1_000_000</span>,</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>        path<span class="op">=</span><span class="va">None</span>,</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>        task<span class="op">=</span>fun_control[<span class="st">"task"</span>],)</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>test_tuned(net<span class="op">=</span>model_default, test_dataset<span class="op">=</span>test, </span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>        loss_function<span class="op">=</span>fun_control[<span class="st">"loss_function"</span>],</span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>        metric<span class="op">=</span>fun_control[<span class="st">"metric_torch"</span>],</span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>        shuffle<span class="op">=</span><span class="va">False</span>, </span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>        device <span class="op">=</span> DEVICE,</span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a>        task<span class="op">=</span>fun_control[<span class="st">"task"</span>],)        </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="evaluation-of-the-tuned-architecture" class="level3" data-number="13.14.4">
<h3 data-number="13.14.4" class="anchored" data-anchor-id="evaluation-of-the-tuned-architecture"><span class="header-section-number">13.14.4</span> Evaluation of the Tuned Architecture</h3>
<p>The following code trains the model <code>model_spot</code>. If <code>path</code> is set to a filename, e.g., <code>path = "model_spot_trained.pt"</code>, the weights of the trained model will be saved to this file.</p>
<div class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>train_tuned(net<span class="op">=</span>model_spot, train_dataset<span class="op">=</span>train,</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>        loss_function<span class="op">=</span>fun_control[<span class="st">"loss_function"</span>],</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>        metric<span class="op">=</span>fun_control[<span class="st">"metric_torch"</span>],</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>        shuffle<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>        device <span class="op">=</span> DEVICE,</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>        path<span class="op">=</span><span class="va">None</span>,</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>        task<span class="op">=</span>fun_control[<span class="st">"task"</span>],)</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>test_tuned(net<span class="op">=</span>model_spot, test_dataset<span class="op">=</span>test,</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>            shuffle<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>            loss_function<span class="op">=</span>fun_control[<span class="st">"loss_function"</span>],</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>            metric<span class="op">=</span>fun_control[<span class="st">"metric_torch"</span>],</span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>            device <span class="op">=</span> DEVICE,</span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>            task<span class="op">=</span>fun_control[<span class="st">"task"</span>],)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>These runs will generate output similar to the following:</p>
<pre class="{raw}"><code>Loss on hold-out set: 1.2267619131326675
Accuracy on hold-out set: 0.58955
Early stopping at epoch 13</code></pre>
</section>
<section id="comparison-with-default-hyperparameters-and-ray-tune" class="level3" data-number="13.14.5">
<h3 data-number="13.14.5" class="anchored" data-anchor-id="comparison-with-default-hyperparameters-and-ray-tune"><span class="header-section-number">13.14.5</span> Comparison with Default Hyperparameters and Ray Tune</h3>
<p><a href="24_spot_torch_regression.html#tbl-comparison">Table&nbsp;<span>14.5</span></a> shows the loss and accuracy of the default model, the model with the hyperparameters from SPOT, and the model with the hyperparameters from <code>ray[tune]</code>. The table shows a comparison of the loss and accuracy of the default model, the model with the hyperparameters from SPOT, and the model with the hyperparameters from <code>ray[tune]</code>. <code>ray[tune]</code> only shows the validation loss, because training loss is not reported by <code>ray[tune]</code></p>
<div id="tbl-comparison" class="anchored">
<table class="table">
<caption>Table&nbsp;13.5: Comparison.</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 25%">
<col style="width: 30%">
<col style="width: 13%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">Validation Loss</th>
<th style="text-align: right;">Validation Accuracy</th>
<th style="text-align: right;">Loss</th>
<th style="text-align: right;">Accuracy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Default</td>
<td style="text-align: right;">2.1221</td>
<td style="text-align: right;">0.2452</td>
<td style="text-align: right;">2.1182</td>
<td style="text-align: right;">0.2425</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>spotPython</code></td>
<td style="text-align: right;">1.2268</td>
<td style="text-align: right;">0.5896</td>
<td style="text-align: right;">1.2426</td>
<td style="text-align: right;">0.5957</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>ray[tune]</code></td>
<td style="text-align: right;">1.1815</td>
<td style="text-align: right;">0.5836</td>
<td style="text-align: right;">-</td>
<td style="text-align: right;">0.5806</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="detailed-hyperparameter-plots" class="level3" data-number="13.14.6">
<h3 data-number="13.14.6" class="anchored" data-anchor-id="detailed-hyperparameter-plots"><span class="header-section-number">13.14.6</span> Detailed Hyperparameter Plots</h3>
<p>The contour plots in this section visualize the interactions of the three most important hyperparameters, <code>l1</code>, <code>l2</code>, and <code>epochs</code>, and <code>optimizer</code> of the surrogate model used to optimize the hyperparameters. Since some of these hyperparameters take fatorial or integer values, sometimes step-like fitness landcapes (or response surfaces) are generated. SPOT draws the interactions of the main hyperparameters by default. It is also possible to visualize all interactions. For this, again refer to the notebook <span class="citation" data-cites="bart23e">(<a href="references.html#ref-bart23e" role="doc-biblioref">Bartz-Beielstein 2023</a>)</span>.</p>
<div class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>filename <span class="op">=</span> <span class="st">"./figures/"</span> <span class="op">+</span> experiment_name</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>spot_tuner.plot_important_hyperparameter_contour(filename<span class="op">=</span>filename)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="fig-contour-0-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="./figures/figures14-torch_maans03_60min_10init_2023-05-19_16-34-33_contour_0_1.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;13.5: Contour plot of the loss as a function of <code>l1</code> and <code>l2</code>, i.e., the number of neurons in the layers.</figcaption>
</figure>
</div>
<div id="fig-contour-0-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="./figures/figures14-torch_maans03_60min_10init_2023-05-19_16-34-33_contour_0_3.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;13.6: Contour plot of the loss as a function of the number of epochs and the neurons in layer <code>l1</code>.</figcaption>
</figure>
</div>
<div id="fig-contour-0-4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="./figures/figures14-torch_maans03_60min_10init_2023-05-19_16-34-33_contour_0_4.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;13.7: Contour plot of the loss as a function of the optimizer and the neurons in layer <code>l1</code>.</figcaption>
</figure>
</div>
<div id="fig-contour-1-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="./figures/figures14-torch_maans03_60min_10init_2023-05-19_16-34-33_contour_1_3.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;13.8: Contour plot of the loss as a function of the number of epochs and the neurons in layer <code>l2</code>.</figcaption>
</figure>
</div>
<div id="fig-contour-1-4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="./figures/figures14-torch_maans03_60min_10init_2023-05-19_16-34-33_contour_1_4.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;13.9: Contour plot of the loss as a function of the optimizer and the neurons in layer <code>l2</code>.</figcaption>
</figure>
</div>
<div id="fig-contour-3-4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="./figures/figures14-torch_maans03_60min_10init_2023-05-19_16-34-33_contour_3_4.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;13.10: Contour plot of the loss as a function of the optimizer and the number of epochs.</figcaption>
</figure>
</div>
<p>The figures (<a href="#fig-contour-0-1">Figure&nbsp;<span>13.5</span></a> to <a href="#fig-contour-3-4">Figure&nbsp;<span>13.10</span></a>) show the contour plots of the loss as a function of the hyperparameters. These plots are very helpful for benchmark studies and for understanding neural networks. <code>spotPython</code> provides additional tools for a visual inspection of the results and give valuable insights into the hyperparameter tuning process. This is especially useful for model explainability, transparency, and trustworthiness. In addition to the contour plots, <a href="24_spot_torch_regression.html#fig-parallel">Figure&nbsp;<span>14.7</span></a> shows the parallel plot of the hyperparameters.</p>
<div class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>spot_tuner.parallel_plot()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="fig-parallel" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="./figures/parallel.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Figure&nbsp;13.11: Parallel plot</figcaption>
</figure>
</div>
</section>
</section>
<section id="sec-summary" class="level2" data-number="13.15">
<h2 data-number="13.15" class="anchored" data-anchor-id="sec-summary"><span class="header-section-number">13.15</span> Summary and Outlook</h2>
<p>This tutorial presents the hyperparameter tuning open source software <code>spotPython</code> for <code>PyTorch</code>. To show its basic features, a comparison with the “official” <code>PyTorch</code> hyperparameter tuning tutorial <span class="citation" data-cites="pyto23a">(<a href="references.html#ref-pyto23a" role="doc-biblioref">PyTorch 2023a</a>)</span> is presented. Some of the advantages of <code>spotPython</code> are:</p>
<ul>
<li>Numerical and categorical hyperparameters.</li>
<li>Powerful surrogate models.</li>
<li>Flexible approach and easy to use.</li>
<li>Simple JSON files for the specification of the hyperparameters.</li>
<li>Extension of default and user specified network classes.</li>
<li>Noise handling techniques.</li>
<li>Interaction with <code>tensorboard</code>.</li>
</ul>
<p>Currently, only rudimentary parallel and distributed neural network training is possible, but these capabilities will be extended in the future. The next version of <code>spotPython</code> will also include a more detailed documentation and more examples.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Important: This tutorial does not present a complete benchmarking study <span class="citation" data-cites="bart20gArxiv">(<a href="references.html#ref-bart20gArxiv" role="doc-biblioref">Bartz-Beielstein et al. 2020</a>)</span>. The results are only preliminary and highly dependent on the local configuration (hard- and software). Our goal is to provide a first impression of the performance of the hyperparameter tuning package <code>spotPython</code>. To demonstrate its capabilities, a quick comparison with <code>ray[tune]</code> was performed. <code>ray[tune]</code> was chosen, because it is presented as “an industry standard tool for distributed hyperparameter tuning.” The results should be interpreted with care.</p>
</div>
</div>
</section>
<section id="sec-appendix" class="level2" data-number="13.16">
<h2 data-number="13.16" class="anchored" data-anchor-id="sec-appendix"><span class="header-section-number">13.16</span> Appendix</h2>
<section id="sample-output-from-ray-tunes-run" class="level3" data-number="13.16.1">
<h3 data-number="13.16.1" class="anchored" data-anchor-id="sample-output-from-ray-tunes-run"><span class="header-section-number">13.16.1</span> Sample Output From Ray Tune’s Run</h3>
<p>The output from <code>ray[tune]</code> could look like this <span class="citation" data-cites="pyto23b">(<a href="references.html#ref-pyto23b" role="doc-biblioref">PyTorch 2023b</a>)</span>:</p>
<pre class="{raw}"><code>Number of trials: 10 (10 TERMINATED)
------+------+-------------+--------------+---------+------------+--------------------+
|   l1 |   l2 |          lr |   batch_size |    loss |   accuracy | training_iteration |
+------+------+-------------+--------------+---------+------------+--------------------|
|   64 |    4 | 0.00011629  |            2 | 1.87273 |     0.244  |                  2 |
|   32 |   64 | 0.000339763 |            8 | 1.23603 |     0.567  |                  8 |
|    8 |   16 | 0.00276249  |           16 | 1.1815  |     0.5836 |                 10 |
|    4 |   64 | 0.000648721 |            4 | 1.31131 |     0.5224 |                  8 |
|   32 |   16 | 0.000340753 |            8 | 1.26454 |     0.5444 |                  8 |
|    8 |    4 | 0.000699775 |            8 | 1.99594 |     0.1983 |                  2 |
|  256 |    8 | 0.0839654   |           16 | 2.3119  |     0.0993 |                  1 |
|   16 |  128 | 0.0758154   |           16 | 2.33575 |     0.1327 |                  1 |
|   16 |    8 | 0.0763312   |           16 | 2.31129 |     0.1042 |                  4 |
|  128 |   16 | 0.000124903 |            4 | 2.26917 |     0.1945 |                  1 |
+-----+------+------+-------------+--------------+---------+------------+--------------------+
Best trial config: {'l1': 8, 'l2': 16, 'lr': 0.00276249, 'batch_size': 16, 'data_dir': '...'}
Best trial final validation loss: 1.181501
Best trial final validation accuracy: 0.5836
Best trial test set accuracy: 0.5806</code></pre>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-bart21i" class="csl-entry" role="listitem">
Bartz, Eva, Thomas Bartz-Beielstein, Martin Zaefferer, and Olaf Mersmann, eds. 2022. <em><span class="nocase">Hyperparameter Tuning for Machine and Deep Learning with R - A Practical Guide</span></em>. Springer.
</div>
<div id="ref-bart23e" class="csl-entry" role="listitem">
Bartz-Beielstein, Thomas. 2023. <span>“<span>PyTorch</span> Hyperparameter Tuning with <span>SPOT</span>: Comparison with <span>Ray Tuner</span> and Default Hyperparameters on <span>CIFAR10</span>.”</span> <a href="https://github.com/sequential-parameter-optimization/spotPython/blob/main/notebooks/14_spot_ray_hpt_torch_cifar10.ipynb">https://github.com/sequential-parameter-optimization/spotPython/blob/main/notebooks/14_spot_ray_hpt_torch_cifar10.ipynb</a>.
</div>
<div id="ref-bart20gArxiv" class="csl-entry" role="listitem">
Bartz-Beielstein, Thomas, Carola Doerr, Jakob Bossek, Sowmya Chandrasekaran, Tome Eftimov, Andreas Fischbach, Pascal Kerschke, et al. 2020. <span>“Benchmarking in Optimization: Best Practice and Open Issues.”</span> arXiv. <a href="https://arxiv.org/abs/2007.03488">https://arxiv.org/abs/2007.03488</a>.
</div>
<div id="ref-mont20a" class="csl-entry" role="listitem">
Montiel, Jacob, Max Halford, Saulo Martiello Mastelini, Geoffrey Bolmier, Raphael Sourty, Robin Vaysse, Adil Zouitine, et al. 2021. <span>“River: Machine Learning for Streaming Data in Python.”</span>
</div>
<div id="ref-pyto23a" class="csl-entry" role="listitem">
PyTorch. 2023a. <span>“Hyperparameter Tuning with Ray Tune.”</span> <a href="https://pytorch.org/tutorials/beginner/hyperparameter_tuning_tutorial.html">https://pytorch.org/tutorials/beginner/hyperparameter_tuning_tutorial.html</a>.
</div>
<div id="ref-pyto23b" class="csl-entry" role="listitem">
———. 2023b. <span>“Training a Classifier.”</span> <a href="https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html">https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html</a>.
</div>
</div>
</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Alternatively, the source code can be downloaded from gitHub: <a href="https://github.com/sequential-parameter-optimization/spotPython">https://github.com/sequential-parameter-optimization/spotPython</a>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>We were not able to install <code>Ray Tune</code> on our system. Therefore, we used the results from the <code>PyTorch</code> tutorial.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./12_spot_hpt_torch_cifar10.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Hyperparameter Tuning: PyTorch wth cifar10 Data</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./24_spot_torch_regression.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Hyperparameter Tuning for PyTorch With <code>spotPython</code>: Regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>